function createRemoteRun(remoteHost, matlabVersion)
    % BaseTools.createRemoteRun - Generates a context-aware remote execution script.
    % Handles both 'Matlab' subfolder (Research) and Project Root (GitHub) styles.
    
    if nargin < 1 || isempty(remoteHost), remoteHost = 'atlas'; end
    if nargin < 2 || isempty(matlabVersion), matlabVersion = 'R2026a'; end

    % 1. CONTEXT DISCOVERY
    localDir = pwd;
    [~, folderName] = fileparts(localDir);
    
    % Detection: Research style (inside Matlab/) vs GitHub style (Project Root)
    if strcmpi(folderName, 'Matlab')
        projectRoot = fileparts(localDir);
    else
        projectRoot = localDir;
    end
    [~, projectName] = fileparts(projectRoot);

    % 2. LIBRARY DISCOVERY
    githubRoot = getenv('HEMINGWAY_LAB_ROOT');
    if isempty(githubRoot)
        githubRoot = fullfile(char(java.lang.System.getProperty('user.home')), 'Documents', 'GitHub');
    end

    scriptName = sprintf('%s_run.sh', remoteHost);
    
    % 3. BASH TEMPLATE
    bashTemplate = [...
        '#!/bin/bash\n\n', ...
        '# --- 1. CONFIGURATION ---\n', ...
        'REMOTE_HOST="' remoteHost '" \n', ...
        'MATLAB_APP="/Applications/MATLAB_' matlabVersion '.app/bin/matlab"\n\n', ...
        'LOCAL_LIB_ROOT="' githubRoot '/"\n', ...
        'LOCAL_DIR=$(pwd)\n', ...
        'DIR_NAME=$(basename "$LOCAL_DIR")\n\n', ...
        '# Context Detection\n', ...
        'if [ "$DIR_NAME" == "Matlab" ]; then\n', ...
        '    PROJECT_NAME=$(basename $(dirname "$LOCAL_DIR"))\n', ...
        '    REMOTE_REL_PATH="Matlab"\n', ...
        'else\n', ...
        '    PROJECT_NAME="$DIR_NAME"\n', ...
        '    REMOTE_REL_PATH="."\n', ...
        'fi\n\n', ...
        '# Remote paths\n', ...
        'REMOTE_HOME=$(ssh "$REMOTE_HOST" "echo \\$HOME")\n', ...
        'REMOTE_GITHUB_ROOT="$REMOTE_HOME/Documents/GitHub"\n', ...
        'REMOTE_RESEARCH_ROOT="$REMOTE_HOME/Documents/Research"\n', ...
        'REMOTE_PROJECT_PATH="$REMOTE_RESEARCH_ROOT/$PROJECT_NAME"\n', ...
        'REMOTE_EXEC_DIR="$REMOTE_PROJECT_PATH/$REMOTE_REL_PATH"\n\n', ...
        '# --- 2. HELPERS ---\n', ...
        'function log_section() {\n', ...
        '    printf "\\n\\n==========================================================\\n"\n', ...
        '    printf ">>> %%s\\n" "$1"\n', ...
        '    printf "==========================================================\\n"\n', ...
        '}\n\n', ...
        '# --- 3. SPECIAL COMMANDS (stop / status / watch) ---\n', ...
        'if [ "$1" == "stop" ]; then\n', ...
        '    log_section "Stopping MATLAB on $REMOTE_HOST"\n', ...
        '    ssh "$REMOTE_HOST" "pkill -f MATLAB && echo ''Sent stop signal.'' || echo ''None found.''"\n', ...
        '    exit 0\n', ...
        'fi\n\n', ...
        'if [ "$1" == "status" ]; then\n', ...
        '    log_section "Snapshot of Atlas Output"\n', ...
        '    ssh "$REMOTE_HOST" "tail -n 20 \\"$REMOTE_EXEC_DIR/batch_output.log\\" | tr -cd ''\\11\\12\\15\\40-\\176''"\n', ...
        '    log_section "Process Resources"\n', ...
        '    ssh "$REMOTE_HOST" "ps -rc -o pid,pcpu,pmem,start,command | grep -i MATLAB | grep -v grep || echo ''Not running.''"\n', ...
        '    printf "\\nSentinel Status:\\n"\n', ...
        '    ssh "$REMOTE_HOST" "ls -lh \\"$REMOTE_EXEC_DIR/JOB_FINISHED.mat\\" 2>/dev/null || echo ''No Sentinel found in $REMOTE_REL_PATH.'' "\n', ...
        '    exit 0\n', ...
        'fi\n\n', ...
        'if [ "$1" == "watch" ]; then\n', ...
        '    log_section "Streaming Atlas Output (Ctrl+C to stop)"\n', ...
        '    ssh "$REMOTE_HOST" "tail -f \\"$REMOTE_EXEC_DIR/batch_output.log\\""\n', ...
        '    exit 0\n', ...
        'fi\n\n', ...
        '# --- 4. DEPLOYMENT ---\n', ...
        'if ssh "$REMOTE_HOST" "pgrep -f MATLAB > /dev/null"; then\n', ...
        '    printf "\\nERROR: MATLAB is already running on $REMOTE_HOST.\\n"\n', ...
        '    exit 1\n', ...
        'fi\n\n', ...
        'log_section "Syncing Libraries to $REMOTE_HOST"\n', ...
        'rsync -avzL --delete --exclude ''.git/'' --exclude ''.gitignore'' --exclude ''.DS_Store'' "$LOCAL_LIB_ROOT" "$REMOTE_HOST":"\\"$REMOTE_GITHUB_ROOT/\\""\n\n', ...
        'log_section "Syncing Project Code: $PROJECT_NAME"\n', ...
        'rsync -avzL --delete --exclude ''.git/'' --exclude ''Archive/'' --exclude ''.DS_Store'' "$LOCAL_DIR/" "$REMOTE_HOST":"\\"$REMOTE_EXEC_DIR/\\""\n\n', ...
        'log_section "Launching Job on $REMOTE_HOST"\n', ...
        'ssh "$REMOTE_HOST" << EOF\n', ...
        '    mkdir -p "$REMOTE_EXEC_DIR"\n', ...
        '    mkdir -p "$REMOTE_PROJECT_PATH/Data"\n', ...
        '    mkdir -p "$REMOTE_PROJECT_PATH/Figures"\n', ...
        '    rm -f "$REMOTE_EXEC_DIR/JOB_FINISHED.mat"\n', ...
        '    export HEMINGWAY_LAB_ROOT="$REMOTE_GITHUB_ROOT"\n', ...
        '    cd "$REMOTE_EXEC_DIR"\n', ...
        '    nohup $MATLAB_APP -batch "setup; batch_main; exit" > batch_output.log 2>&1 &\n', ...
        '    echo "Job submitted! Use ./ ' scriptName ' watch to check in."\n', ...
        'EOF\n' ...
    ];

    % 4. WRITE & SET PERMISSIONS
    fid = fopen(scriptName, 'w');
    fprintf(fid, bashTemplate);
    fclose(fid);
    system(['chmod +x ', scriptName]);
    
    fprintf('Created %s for project: %s\n', scriptName, projectName);
end